#!/bin/sh

  case $1 in
    "--help" | "-h")
	echo "show packages with dependencies for given binary. Example:"
	echo
	echo "$0 /bin/bash"
	;;
    "--version" | "-v" )
	echo "ldd2debs v0.1"
	exit 0
	;;
    *)
	ldd $1 | awk '/=>/{print $(NF-1)}'  |  while read n; do apt-file search $n; done |   awk '{print $1}' | sed 's/://' | sort | uniq
	;;
  esac
