---
- name: prepare Jenkins drones
  hosts: jenkins
  become: true
  become_method: sudo
  roles:
    - role: jenkins-drone
  tasks:
    - name: Is /var/ mounted ?
      command: mountpoint -q /var/
      register: volume_stat
      failed_when: False
      changed_when: False

    - name: Instal docker only to external drive
      include_role: 
        name: 'docker'
      when: volume_stat.rc == 0
