.TH LDD2DEBS 1 "October 2023" "v0.1" "ldd2debs manual"

.SH NAME
ldd2debs \- show packages with dependencies for a given binary

.SH SYNOPSIS
.B ldd2debs
[\fIoptions\fR] \fIbinary\fR

.SH DESCRIPTION
.B ldd2debs
is a script that shows the packages with dependencies for a given binary.

.SH OPTIONS
.TP
.B \-\-help, \-h
Show help message and usage example.
.TP
.B \-\-version, \-v
Show the version of the script.

.SH EXAMPLES
To show the packages with dependencies for /bin/bash:
.PP
.B ldd2debs /bin/bash

.SH AUTHOR
Vítězslav Dvořák <info@vitexsoftware.cz>

.SH LICENSE
This script is licensed under the MIT License.

.SH SEE ALSO
.BR ldd (1),
.BR apt-file (1),
.BR awk (1),
.BR sed (1),
.BR sort (1),
.BR uniq (1)