#!/bin/sh
# postinst script for buildimages

set -e

	docker pull vitexsoftware/debian:lts
	docker pull vitexsoftware/debian:oldstable
	docker pull vitexsoftware/debian:stable
	docker pull vitexsoftware/debian:testing
	docker pull vitexsoftware/ubuntu:stable
	docker pull vitexsoftware/ubuntu:testing


#DEBHELPER#

exit 0
