name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Multiple platforms feature is currently not supported for docker driver.
      run: docker buildx create --use
    - name: Build the Docker image
      run: make buildx
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2.4.3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: peterevans/dockerhub-description
        short-description: ${{ github.event.repository.description }}
